### ISSUE TITLE
Feedback from Rachel Golin - USAID

### ISSUE THREAD

**Issue by nmcdavid** [ICPI/HIV-TB-Diagnosis-Cluster#8]
Thanks for sharing, Nashiva, and apologies for the late reply. I hope last week's call went well.

A few quick thoughts:

- Wow!! Thanks for all of your work! I really like being able to have high level view across OUs with the option to do a deeper dive. This dashboard seems much more user friendly than Panorama.
- I likely missed this, so feel free to point me in the right direction -- any thoughts on comparing the PMTCT_EID indicator with PMTCT_STAT as a proxy for EID coverage? Again, I may have missed this. 
- On the 3rd tab (PMTCT_EID Proxy Positivity) -- is this positivity or yield? I know the terms are often used interchangeably and I'm trying to force myself to use them correctly. :)
- On the 4th tab (PMTCT_HEI_POS Linkage) - Just want to confirm this is proxy linkage. Also, do you know if the "positives" represent DBS results sent and received before 2m of age? Or just sent before 2m of age? 
- In general, I have some reservations with using HTS_TST for infants as some countries have universal rapid testing for all babies regardless of HIV exposure -- I'm not sure how, if at all, this may impact data collection/reporting despite guidance to not include these data points. Do you know if any quick checks have been done to ensure that HTS_TST < 1y is less than PMTCT_EID 0 - 12m for all OUs as all positive rapid tests (HTS_TST) should be followed up with a DBS (PMTCT_EID).

**Comment by KatieOC** [comment]
i moved this feedback to issue #6

**Comment by KatieOC** [comment]
closing this issue.
